### ISSUE TITLE
is project abandonned ?

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#30]
Hi !

   It seems that the project is not maintained anymore, as all urls are giving 404 errors.
@qnxdev,  This is a very useful site, and there are still many active users of bb10.
Would you be ready to transfer the data to another maintainer ?

Best Regards,

**Comment by swisscdn** [comment]
The project was live, but not maintained. 

Few months ago I received a trademark violation notice from BlackBerry, threatening to take down the site because of its name **BlackBerry Store**

I stopped development on this when I stopped using BB10. I still love BB10, no OS has satisfied me that much. 


If you guys still want to keep it live you can fork or put a Pull request on this code with all references to **BlackBerry** or **BB**  removed

**Comment by karawitan** [comment]
Ok thank you very much for the answer. You might be contacted soon by a member of the Berrymuch community.

Many thanks for your efforts so far, this is a great project.

**Comment by qnxdev** [comment]
Deleted my old response but adding it back here.

Basically it got a trademark violation notice from BlackBerry. I believe anyone can fork it or put PR on it to remove any reference to **BlackBerry or BB** and we can host it back up.

I stopped using BB10, but I'd still say it's the best OS I ever used.
